heat_template_version: 2013-05-23

parameters:
   name:
     type: string
     label: instance name
   ipaddr:
     type: string
     label: server ip
   public_key:
     type: string
     label: public key
   private_key:
     type: string
     label: private key
   key:
     type: string
     label: key name

resources:

   instance:
     type: OS::Nova::Server
     properties:
       name: { get_param: name }
       flavor: m1.small
       image: centos-6.6-x86_64
       personality:
         /root/.ssh/coms_rsa: { get_param: private_key }
       networks:
         - network: private
       key_name: { get_param: key }
       user_data_format: RAW
       user_data:
         str_replace:
           template: |
             #!/bin/bash
             chmod 0700 /root/.ssh/coms_rsa
             echo $PUBLIC_KEY
             echo $PUBLIC_KEY >> /home/centos/.ssh/authorized_keys
           params:
             $PUBLIC_KEY: { get_param: public_key }
