heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: centos-6.6-x86_64
  flavor:
    type: string
    label: Flavor
    description: Type of instance
    default: m1.small
  key:
    type: string
    label: Key name
    description: name of key-pair to be used for compute instance
    default: cloud
  private_network:
    type: string
    label: Private network name of id
    description: Network to attach instance to
    default: private

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      name: centos-6.6-20gb
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: {get_param: key }
      user_data_format: RAW
      networks:
        - network: { get_param: private_network }

outputs:
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [my_instance, first_address] }

