heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameters:
  prefix:
    type: string
    label: domain prefix
    default: node.dc1.consul
  vmname: 
    type: string
    label: VM name 
    default: centos-6.6-20gb
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: centos-6.6-x86_64
  flavor:
    type: string
    label: Flavor
    description: Type of instance
    default: m1.large
  key:
    type: string
    label: Key name
    description: name of key-pair to be used for compute instance
    default: cloud
  private_network:
    type: string
    label: Private network name of id
    description: Network to attach instance to
    default: df67a5c1-1340-459f-92e9-ac95e351ceb1
  private_subnet_id:
    type: string
    label: Private network name of id
    description: Network to attach instance to
    default: 5455e630-dabe-46e7-a05e-aacd94ba5998 
  public_network:
    type: string
    label: Public network name or id
    description: Public network with floating IP addresses
    default: public
  private_static:
    type: string
    default: 0f8de7c7-f5cf-40e1-8273-283967532f1c 
  shared_ip:
    type: string
    description: Fixed ip
    default: 172.0.33.10
  fqdn:
    type: string
    description: fqdn for all nodes
    default: node.dc1.consul
  client:
    type: number
    description: number of client nodes
    default: 1
  node_instances:
    type: number
    description: Number of instances to create
    default: 1

resources:
  instance_port0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_static }
      fixed_ips:
        - ip_address: { get_param: shared_ip }

  instance_port1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }

  stack-string:
    type: OS::Heat::RandomString
    properties:
      length: 6
      sequence: lettersdigits

  coms:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name:
        str_replace:
          template: hadoop-$stackstr-coms
          params:
            $stackstr:
              get_attr:
                - stack-string
                - value

  ambari_server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: $name.$prefix
          params:
            $name: { get_param: vmname }
            $prefix: { get_param: prefix }
      flavor: m1.small 
      image: { get_param: image }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: instance_port0 }
        - port: { get_resource: instance_port1 }
      personality:
        /root/.ssh/coms_rsa:
          get_attr:
            - coms
            - private_key
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            chmod 0700 /root/.ssh/coms_rsa
            
            mkdir -p /etc/puppet/hiera
            TMP_PATH=`mktemp -d`
            git clone https://github.com/thbeh/puppetfiles.git $TMP_PATH

            cat << EOF >> $TMP_PATH/puppet/server.pp
            class { 'jdk_oracle':
              version => "8"
            }
            EOF

            cp -R $TMP_PATH/puppet/* /etc/puppet/
            cp -R $TMP_PATH/hiera/hiera.yaml /etc/puppet/
            cp -R $TMP_PATH/hiera/* /etc/puppet/hiera/

            puppet apply $TMP_PATH/puppet/server.pp
            
          params:
            $PUBLIC_KEY: { get_attr: [ coms, public_key ] } 

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }
      port_id: { get_resource: instance_port1 }

  client_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: client }
      resource_def: 
        type: HDP::Hadoop::Nodes 
        properties:
          name:
            str_replace:
              template: client%index%.$prefix
              params:
                $prefix: { get_param: prefix }
          ipaddr: { get_attr: [ instance_port1, fixed_ips, 0, ip_address ] }
          key: { get_param: key }
          private_key: { get_attr: [ coms, private_key ] }
          public_key:
            get_attr:
              - coms
              - public_key

  server_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: node_instances }
      resource_def: 
        type: HDP::Hadoop::Nodes 
        properties:
          name:
            str_replace:
              template: node%index%.$prefix
              params:
                $prefix: { get_param: prefix }
          ipaddr: { get_attr: [ instance_port1, fixed_ips, 0, ip_address ] }
          key: { get_param: key }
          private_key: { get_attr: [ coms, private_key ] }
          public_key:
            get_attr:
              - coms
              - public_key

