heat_template_version: 2013-05-23

parameters:
   name:
     type: string
     label: instance name
   ipaddr:
     type: string
     label: server ip
   public_key:
     type: string
     label: public key
   private_key:
     type: string
     label: private key

resources:

   instance:
     type: OS::Nova::Server
     properties:
       name: { get_param: name }
       flavor: m1.small
       image: centos-6.6-x86_64
       key_name: cloud
       networks:
         - network: private
       user_data_format: RAW
       user_data:
         str_replace:
           template: |
             #!/bin/bash -v
             rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm
             yum install -y puppet
             echo "$ipaddr" puppet >> /etc/hosts
             echo "$public_key" > /root/.ssh/keys
           params:
             $ambari_ip: { get_param: ipaddr }

